### ISSUE TITLE
The extension is not loaded correctly. The local icon folder "fileicons" is not include the "images" folder. 

### ISSUE THREAD

**Issue by HymseMeow** [ryohidaka/kawaii-icons#6]
### The extension is not loaded when I set it as my icon theme. 
When I look for the cause of the problem in my local folder, I find that the local folder doesn't contain this folder "./fileicons/images". 
Here's a screenshot of my folder. 
![image](https://github.com/ryohidaka/kawaii-icons/assets/86318370/70b49547-aa5a-414b-9b02-e247e27323cf)
This "./fileicons/images" folder is a reference to [SAWARATSUKI's repo](https://github.com/SAWARATSUKI/ServiceLogos), but it isn't cloned directly, and it does not exist in my local folder. 
I think it's the main reason why this extension is not loaded correctly. And I hope it can be fixed quickly. :P

At last, please forgive me for my terrible English(┬┬﹏┬┬).

**Comment by ryohidaka** [comment]
@LuoYuLose 

Thank you for contacting us.

You are correct, the submodules were ignored during packaging.

We have released `v0.3.1`, which fixes the problem without using submodules as soon as possible.

We hope you will check it.

谢谢

**Comment by mahirandigital** [comment]
![image](https://github.com/ryohidaka/kawaii-icons/assets/88936459/8b33ab8d-2d8f-4860-87e5-e60199c91b17)

not working for vscode mac

**Comment by ryohidaka** [comment]
@mahirandigital 

> not working for vscode mac

JSON is not supported because it is not included in the following repositories.
- https://github.com/SAWARATSUKI/ServiceLogos

If not supported, the default file icon will be displayed.

**Comment by mahirandigital** [comment]
> @mahirandigital
> 
> > not working for vscode mac
> 
> JSON is not supported because it is not included in the following repositories.
> 
> * https://github.com/SAWARATSUKI/ServiceLogos
> 
> If not supported, the default file icon will be displayed.

![image](https://github.com/ryohidaka/kawaii-icons/assets/88936459/5aea9216-d4be-4fb8-9134-e703ca6dd1c8)
![image](https://github.com/ryohidaka/kawaii-icons/assets/88936459/403fdfe0-8532-459a-8d52-26283708195b)

still not loaded in dart file

**Comment by ryohidaka** [comment]
@mahirandigital 
>still not loaded in dart file

dart is also not yet supported because the logo image has not been created.

**Comment by mahirandigital** [comment]
![image](https://github.com/ryohidaka/kawaii-icons/assets/88936459/cc0ca978-06e5-4f1a-ae32-f0f2a92080a1)
why my php not loaded? i thought the logo was created
